version: '2.0'
services:
    etcd:
        image: "quay.io/coreos/etcd"
        volumes:
        - ${PWD}/etcd-data/:/etcd-data
        command:
        - /usr/local/bin/etcd
        - --data-dir=/etcd-data 
        - --listen-client-urls=http://0.0.0.0:2379
        - --advertise-client-urls=http://127.0.0.1:2379
        - --debug
        ports:
        - "2379:2379"
#    mosquitto:
#        image: eclipse-mosquitto:latest
#        volumes:
#        - ${PWD}/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
#        ports:
#        - "1883:1883"
#        - "9001:9001"
    crossbar:
        image: crossbario/crossbar:cpy3
        volumes:
        - ${PWD}/crossbar/crossbar.json:/node/.crossbar/config.json
        command:
        - --loglevel
        - debug
        ports:
        - "8080:8080"
        - "8000:8000"
